name: CD - Nexus to ECR + ECS

on:
  workflow_run:
    workflows: ["Node.js CICD"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: Agent-1

    steps:
      # -------------------------
      # AWS AUTH
      # -------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # -------------------------
      # NEXUS LOGIN
      # -------------------------
      - name: Login to Nexus
        run: |
          echo "${{ secrets.NEXUS_PASSWORD }}" | docker login \
          http://${{ vars.NEXUS_HOST }} \
          -u "${{ secrets.NEXUS_USERNAME }}" --password-stdin

      # -------------------------
      # PULL FROM NEXUS
      # -------------------------
      - name: Pull images
        run: |
         # docker pull ${{ vars.NEXUS_HOST }}/docker-hosted/backend:latest
          docker pull ${{ vars.NEXUS_HOST }}/docker-hosted/frontend:latest

      # -------------------------
      # TAG & PUSH TO ECR
      # -------------------------
      - name: Push images to ECR
        run: |
          

          # docker tag ${{ vars.NEXUS_HOST }}/docker-hosted/backend:latest \
          # $ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/backend:latest

          docker tag ${{ vars.NEXUS_HOST }}/docker-hosted/frontend:latest \
          $ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/frontend:latest

          # docker push $ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/backend:latest
          docker push $ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/frontend:latest

      # -------------------------
      # ECS DEPLOY
      # -------------------------
      - name: Force ECS redeploy (frontend)
        run: |
          aws ecs update-service \
            --cluster devsecops-cluster \
            --service frontend \
            --force-new-deployment

      

